version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: imdb
      POSTGRES_USER: kieransweetman
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - imdb-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  springboot-app:
    image: openjdk:17-jdk-slim
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/imdb
      SPRING_DATASOURCE_USERNAME: kieransweetman
      SPRING_DATASOURCE_PASSWORD: yourpassword
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - imdb-network
   

volumes:
  postgres_data:

networks:
  imdb-network: